#
# Create a program that will play the “cows and bulls” game with the user. The game works like this:
#
# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number.
# For every digit that the user guessed correctly in the correct place, they have a “cow”.
# For every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess,
# tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, the game is over.
# Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.
#
# Say the number generated by the computer is 1038. An example interaction could look like this:
#
#   Welcome to the Cows and Bulls Game!
#   Enter a number:
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 1 bull
#   ...
# Until the user guesses the number.
import random
def cows_and_bulls():
    cows = []
    bulls = []
    random_number = random.randint(1000, 9999)
    random_number_split = [i for i in str(random_number)]

    number_of_guesses = 1
    while number_of_guesses < 11:
        guess = int(input("guess a 4 digit number: "))
        guess_split = [i for i in str(guess)]

        if guess == random_number:
            print("the game is over")
            return
        for i in range(len(guess_split)):
            if guess_split[i] == random_number_split[i]:
                cows.append("cow")
            elif guess_split[i] in random_number_split:
                bulls.append("bull")

        print(f"you have {len(cows)} COWS and {len(bulls)} BULLS")
        print(f"toy have guessed {number_of_guesses} times")
        number_of_guesses += 1


cows_and_bulls()
